repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
    -   id: debug-statements
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending

-   repo: https://github.com/jazzband/pip-tools
    rev: 6.2.0
    hooks:
    -   id: pip-compile
        name: pip-compile setup.py
        files: ^(setup\.py|requirements\.txt)$
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.21.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.3b0]
-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        args: [--max-line-length=131]
